export const ADD_REMINDER = "ADD_REMINDER";
export const ADD_REMINDER_SUCCESS = "ADD_REMINDER_SUCCESS";
export const SET_CURRENT_REMINDER = "SET_CURRENT_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
